### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by mhalmagiu**
Seems like some of the improvements didn't make it in.

Also, want to check the PR anyway.

### CODE REVIEW

**Review by sjagoe — CHANGES_REQUESTED** [review]
This directly reverts all of the fixes?

**Comment by sjagoe** [comment]
It also always force-pushes master.

**Comment by mhalmagiu** [comment]
> It also always force-pushes master.

That's intentional, to overwrite any existing changes in the branch

**Review by sjagoe — APPROVED** [review]

**Comment by sjagoe** [comment]
Yes, with all the revert I missed that it was the same push

**Review by fisherking — APPROVED** [review]

**Pull request merged**
